version: "3"
services:
  # static file/content server
  serv:
    build: serv/
    restart: unless-stopped
    ports:
      - 8100:8100
    volumes:
      - ~/viewn-content:/mnt/content:rw

  # postgres db. environment variables are in .env
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

  # rest api stood up in front of postgres
  api:
    build: api/
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8090:8090

volumes:
  postgres-data:
